export const ADD_TO_CART_PRODUCT = 'ADD_TO_CART_PRODUCT';
export const SUB_TO_CART_PRODUCT = 'SUB_TO_CART_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';
